### ISSUE TITLE
ResNet flatten layer shape issue

### ISSUE THREAD

**Issue by rraayyii** [liao2000/ML-Notebook#1]
Hi,
First of all thanks for sharing. I ran your ResNet code and found your implementation of the torch.flatten function appears to be outdated. According to your syntax, the batch_size dimension will also be flattened, resulting in an incorrect shape before being passed to the fully connected layer.

**Comment by ksw2000** [comment]
> Hi, First of all thanks for sharing. I ran your ResNet code and found your implementation of the torch.flatten function appears to be outdated. According to your syntax, the batch_size dimension will also be flattened, resulting in an incorrect shape before being passed to the fully connected layer.

Thank you! 
It appears to me that you are right. I checked the same problem on https://stackoverflow.com/questions/60115633/pytorch-flatten-doesnt-maintain-batch-size and fixed my code.

Incorrect:
```py
input = torch.flatten(input)
```

Correct:
```py
input = torch.flatten(input, start_dim=1)
```
